name: dot_navigation_bar
description: Simple smooth animations, providing a nice and cleanUI/UX Bottom Nav Bar.
version: 1.0.1+4
# author: Haptome <haptomee@icloud.com>
homepage: https://github.com/haptome/dot_navigation_bar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
